// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Khz3-iaplLvj2cIIpx7k3H5UJhMqPYE',
    appId: '1:834509259940:web:cc0aa3f81270cd8c4f1231',
    messagingSenderId: '834509259940',
    projectId: 'b2-ebc2e',
    authDomain: 'b2-ebc2e.firebaseapp.com',
    storageBucket: 'b2-ebc2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qUmyZiWslC8gUQtVGD2gTAd3n7T7RJM',
    appId: '1:834509259940:android:70179a8c7b1008ff4f1231',
    messagingSenderId: '834509259940',
    projectId: 'b2-ebc2e',
    storageBucket: 'b2-ebc2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpfzm94AL6DIgm7rA6JTNK7QGrleoGnBs',
    appId: '1:834509259940:ios:592ec02907873f8d4f1231',
    messagingSenderId: '834509259940',
    projectId: 'b2-ebc2e',
    storageBucket: 'b2-ebc2e.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );
}
